title: Brendan King # your name (or website title) here
logo: "/images/BrendanKingHeadshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in ...
  Department of Ocean Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/brendan-king-296035169/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
